apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gcppublic
  namespace: cert-manager
spec:
  acme:
    email: xxxx@xxx.com
    #New enrolments only
    server: https://dv.acme-v02.test-api.pki.goog/directory
    externalAccountBinding:
      keyID: xxxxxx
      keySecretRef:
        name: eab-secret
        key: secret
    privateKeySecretRef:
        name: example-issuer-account-key
    solvers:
    - dns01:
        cloudDNS:
          # The ID of the GCP project
          project: DNS_PROJECT_ID